config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/terms' => 'home#terms'
  get '/about' => 'home#about'
  post '/' => 'home#create', as: 'entries'
  get '/prize/jackpot' => 'prize#jackpot'

  namespace :api do
    get 'address/:btc_address/balance' => 'block_explorer#check_balance'
  end
end

app/models/block_explorer_api.rb
class BlockExplorerApi
  include HTTParty

  attr_reader :btc_address

  def initialize(btc_address)
    @btc_address = btc_address
  end

  def check_balance
    response = HTTParty.get("https://blockexplorer.com/api/addr/#{btc_address}/balance")
    if response == 0
      return 0
    elsif !response.success?
      puts "API failure, response code not success...switching to backup source..."
      return "response code not success" # implement backup source
    else
      return response.parsed_response.to_f / 100000000.0
    end
  end
end

app/models/btc_address.rb
class BtcAddress

  def self.create_with_no_coins(account_nickname)
    generate_account(account_nickname)
  end

  def self.create_with_coins(account_nickname)
    new_address = generate_account(account_nickname)
#    @bc.sendtoaddress(new_address, 5.0)
    @bc.move("", account_nickname, 5.0)
    @bc.generate(5)

    new_address
  end

  private

  def self.generate_account(account_nickname)
    @bc = BtcRemote.connect
    new_address = @bc.getnewaddress
    @bc.setaccount(new_address, account_nickname)

    new_address
  end
end

app/models/btc_balance.rb
class BtcBalance
  attr_reader :btc_address

  def initialize(btc_address)
    @btc_address = btc_address
    @bc = BtcRemote.connect
  end

  def amount
    accounts = @bc.listreceivedbyaddress(0, true)
    my_account = {}

    accounts.each do |account|
      if account["address"] == btc_address
        my_account = account
      end
    end

    my_account["amount"].to_f
  end
end

app/models/btc_entry.rb
#class BtcEntry
#
#  def initialize(entry)
#    @sender = entry.sender
#    @recipient = entry.recipient
#    @gross_amount = entry.amount
#  end
#
#  def submit(entry)
#    @bc = BtcRemote.connect
##    sendmany "fromaccount" {"address":amount,...} ( minconf "comment" ["address",...] )
#    @bc.sendmany ???, recipients
#    @bc.generate(5)
#  end
#
#  def recipients
#    {
#      @recipient: @gross_amount,
#      @us: amount_to_us,
#      Charity.find(entry.charity).btc_address: amount_to_charity
#    }.merge(prize_pool_amounts)
#  end
#
#  def amount_to_us
#    @gross_amount * 0.005
#  end
#
#  def amount_to_charity
#    @gross_amount * 0.005
#  end
#
#  def prize_pool_amounts
#    num_pools = PrizePool.count
#
#    PrizePool.inject({}) do |holder, pool|
#      holder[pool.btc_address] = (@gross_amount * 0.005) / num_pools
#      holder
#    end
#  end
#end

app/models/btc_remote.rb
class BtcRemote
  def self.connect
    # Hans local
    RPC::JSON::Client.new "http://bitcoinrpc:qGIOj9oli0g4YghvPxx4pbgpn1BK9lNm8W8z3pQtgWWXH@127.0.0.1:18332", 1.1

    # Linode
    # RPC::JSON::Client.new "http://warrenv:warrenvPASS@45.79.175.63:18332", 1.1
  end
end

app/models/charity.rb
class Charity < ActiveRecord::Base
  before_create :generate_address
  after_create :set_initial_funds

  # def get_balance
  #   BtcBalance.new(btc_address).amount
  # end

  private

  def set_initial_funds
    update_attributes!(balance: 0.00)
    update_attributes!(lifetime_contributions: 0.00)
  end

  def generate_address
    self.btc_address = BtcAddress.create_with_no_coins("Charity: #{self.name}")
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :total
  validates_numericality_of :total, greater_than_or_equal_to: 0.00001

  validates_presence_of :recipient
  validates_presence_of :charity_id
  validates_acceptance_of :terms
end

app/models/prize_pool.rb
class PrizePool < ActiveRecord::Base
  before_create :generate_address

  def total
    the_entries = get_the_entries

    the_entries.inject(0) do |total, entry|
      total += entry.total * 0.00125
    end
  end

  def get_the_entries
    last_date = Time.now
    first_date = last_date - time_since_last_payout
    time_range = first_date..last_date
    Entry.where(created_at: time_range)
  end

  def my_age
    (Time.now - created_at).to_i
  end

  def time_since_last_payout
    my_age % payout_frequency
  end

  private

  def generate_address
    self.btc_address = BtcAddress.create_with_no_coins("Pool: #{self.name}")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :initialize_balance
  after_create :generate_name
  after_create :generate_address

  validates :name, uniqueness: true

  def get_balance
    balance
  end

  def transfer_bitcoins(recipient, total, charity_id)
    update_attributes!(balance: (self.balance - (total * 1.016)))
    them = User.where(btc_address: recipient).first
    them.update_attributes!(balance: (them.balance + total))
    the_charity = Charity.find(charity_id)
    the_charity.update_attributes!(balance: (the_charity.balance.to_f + (total * 0.005)))
    the_charity.update_attributes!(lifetime_contributions: (the_charity.balance.to_f + (total * 0.005)))
  end

  private

  def initialize_balance
    update_attributes(balance: 5.0)
  end

  def generate_address
    update_attributes!(btc_address: BtcAddress.create_with_no_coins("User: #{name}"))
  end

  def generate_name
    update_attributes!(name: "#{SecureRandom.hex(16)}#{id}")
  end
end

app/controllers/api/block_explorer_controller.rb
module Api
  class BlockExplorerController < ApplicationController

    def check_balance
      @block_explorer_api = BlockExplorerApi.new(params[:btc_address])
      balance = @block_explorer_api.check_balance
      render json: { params[:btc_address] => "#{balance} BTC" }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/entry_controller.rb
class EntryController < ApplicationController

  # def create
  #   @entry = Entry.new(entry_params)
  #   if @entry.save
  #     redirect_to '/', notice: 'You sent the loot!'
  #   else
  #     redirect_to '/'
  #   end
  # end

private

  # def entry_params
  #   params.require(:entry).permit(:recipient, :total)
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :get_prize_pools, :get_charities, :get_users, :get_entry, :get_entries
  before_action :get_user

  def terms
  end

  def about
  end

  def show
  end

  def create
    get_user
    @entry = Entry.new(entry_params)

    if (@user.balance > (@entry.total.to_i * 1.016)) && @entry.save
      @user.transfer_bitcoins(@entry.recipient, @entry.total, @entry.charity_id)

      session[:new_transfer] = true
      redirect_to '/'
    else
      get_prize_pools
      get_charities
      get_users
      get_entries

      render :show
    end
  end

  private

  def get_entries
    @entries = Entry.where(status: 'won').order('created_at DESC').limit(5)
  end

  def get_entry
    @entry = Entry.new
  end

  def get_prize_pools
    @prize_pools = PrizePool.all
  end

  def get_charities
    @charities = Charity.all
  end

  def get_users
    @users = User.all.limit(10)
  end

  def get_user
    @user = User.find_by_name session[:name]

    unless @user
      @user = User.create
      session[:name] = @user.name
      @new_user = true
    else
      @new_user = false
    end
  end

  def entry_params
    params.require(:entry).permit(:recipient, :total, :terms, :charity_id, :sender)
  end
end

app/controllers/prize_controller.rb
class PrizeController < ApplicationController

  def jackpot
    if params[:time_frame] == 'Hourly'
      PayHourlyPrizeJob.perform_now
    elsif params[:time_frame] == 'Daily'
      PayDailyPrizeJob.perform_now
    elsif params[:time_frame] == 'Weekly'
      PayWeeklyPrizeJob.perform_now
    elsif params[:time_frame] == 'Bi-weekly'
      PayBiWeeklyPrizeJob.perform_now
    end

    render json: params

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prize_helper.rb
module PrizeHelper
end

app/views/home/_slideshow.html.erb
<div class='container'>
  <div class='row'>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <% @charities.each_with_index do |charity, index| %>
          <div class="item <%= 'active' if index == 0 %>">
            <div class='fancy-border-box'>
              <%= image_tag charity.logo, class: 'center-block'  %>
              <div class='contribution-banner'>
                Lifetime Contributions to <%= "#{charity.name} #{number_with_precision(charity.lifetime_contributions, precision: 5)}" %> <span class="glyphicon glyphicon-bitcoin"></span>
              </div>
            </div>
          </div>
        <% end %>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/home/_transfer_form.html.erb
<%= form_for @entry, html: {class: "form", role: "form"} do |f| %>

  <div class='double-transfer-boundary'>
    <div class='item-container center-block transfer-left'>
      <div class='fancy-border-box'>
        <h2>1. Send Bitcoin</h2>
        <% if @entry.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
            <ul>
            <% @entry.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="wrapper">
          <%= f.text_field :recipient, class: "form-control", placeholder: 'mzMfmZBhf16dqYncB16R3Fgh3SEdxtYWSw' %>
        </div>
        <br>
        <div class="wrapper">
          <%= f.number_field :total, min: 0.00, step: 0.00001, class: "form-control", placeholder: '0.000000000 BTC' %>
          <%= f.hidden_field :sender, value: @user.btc_address %>
        </div>
        <br>
        <span class='glyphicon glyphicon-arrow-right btn-lg' />
      </div>
    </div>

    <div class='item-container center-block transfer-right'>
      <div class='fancy-border-box'>
        <h2>2. Donate to a Non-Profit</h2>
        <% if @entry.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
            <ul>
            <% @entry.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="wrapper">
          <%= f.select :charity_id, options_for_select(@charities.map{|m| [m.name, m.id]}),
              {include_blank: "Select a Non-Profit"}, {class: "form-control"} %>
        </div>

        <div id="wrapper_last_line" class="form-group text-center">
          <%= f.submit "DO THIS!", class: "btn btn-success btn-lg" %><br>
          <%= f.check_box :terms %> <%= link_to 'I accept the terms', terms_path %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/about.html.erb
<div id="about_content" class="alert-warning">
  <h3>Echo... what now?</h3>
  <p>
    Echocoin is a bitcoin payment service with something a little extra. Each time
    you send a transaction you will contribute to a charity of your choice and you will
    also be entered into each of the prize pools.
  </p>

  <h3>How does it work?</h3>
  <p>
    Echocoin is a three-way partnership between the charities, the developers and
    you! Small donations have a way of adding up and hey; it's kind of exciting! Just
    by using Echocoin you have a chance to win each of the prize pools. If you're
    lucky enough you could even win more than one pool.
  </p>

  <h3>Anything else I should know?</h3>
  <p>
    Yes, since you are doing the lord's work here, you can also enter your email
    address to get a charitable donation certificate. If you choose to enter your
    email you will also get notified if you win a prize pool.
  </p>
</div>

app/views/home/show.html.erb
<div id="transfer_form">
  <%= render 'transfer_form' %>
</div>

<div id="entries_feed">
  <%= render 'slideshow' %>
</div>

<div id="winners" class="">
  <div class='item-container center-block'>
    <h2>Latest Winners</h2>
    <ol>
      <% @entries.each do |entry| %>
        <li><%= entry.sender %></li>
      <% end %>
    </ol>
  </div>
</div>

<% if session[:new_transfer] %>
  <% session.delete :new_transfer %>
  <div class="echocoin-modal modal fade" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div style="background-color: #999;" class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="memberModalLabel">Notice</h4>
        </div>

        <div class="modal-body">
           <p>This is where you would scan the QR code below with your bitcoin wallet software to create a bitcoin transaction.</p>
           <p>For this demo, we'll go ahead and enter you into the prize drawing and pretend that's what happened once you click close.</p>
           <%= image_tag("sample_qr.png") %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if @new_user %>
  <div class="echocoin-modal modal fade" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div style="background-color: #999;" class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="memberModalLabel">Welcome new Echocoin user!</h4>
        </div>

        <div class="modal-body">
          <p>
            During the Rails Rumble, this site does not use real bitcoins and is operating in a simulation mode.
          </p>

          <p>
            You will be able to simulate sending bitcoin to other users of the site
            by selecting a bitcoin address from a dropdown menu.

            Therefore, we are assigning you this test bitcoin address for use during judging.
          </p>

          <div class="bitcoin_address">
            <%= @user.btc_address %>
          </div>

          <p>
            This will display in the upper right as your user id. Other users of the site can send you
            bitcoin and any prize pools that you win will be paid to this address.
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/terms.html.erb
<div id="terms_content" class="alert-warning">
  <h3>What are the EXACT fee totals?</h3>
  <p>
    Here's the breakdown:
    <ul>
      <li>0.5% goes to the charity of your choice</li>
      <li>0.5% goes to the prize pools</li>
      <li>0.5% goes towards running the site</li>
    </ul>
    The only other cost is the price of a bitcoin transaction, which can vary. You
    can read more <%= link_to '*here*', 'https://en.bitcoin.it/wiki/Transaction_fees' %> but
    the total transaction fee should be in the neighborhood of a tenth of one percent.

    The fees are paid by the sender. This means if you send 1.000 BTC, your wallet will be
    charged ≈1.016 BTC (about 1.6%), not too shabby!
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Echocoin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,900,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <script type="text/javascript">
      $(document).ready(function(){
        $(".echocoin-modal").modal('show');
      });
    </script>

    <script type="text/javascript" src="//cdn-gh.firebase.com/btcquote/embed.js"></script>

  </head>

  <body>

    <header>
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag 'echocoin-logo-gray-left.png' %>
        <% end %>
      </div>

      <div id="btc-quote"></div>

    </header>
    <div id="prize-pool-banner">
      <div class='prize-pools-tab'>Prize Pools</div>
      <ul>
        <% @prize_pools.each_with_index do |prize_pool, index| %>
          <li>
            <%= "| " unless index == 0 %>
            <%= " #{prize_pool.name} #{number_with_precision(prize_pool.total, precision: 5)}" %> <span class="glyphicon glyphicon-bitcoin"></span>
          </li>
        <% end %>
      </ul>
    </div>

    <%= yield %>

    <footer>
      <span id="copyright">Copyright &copy;<%= Time.now.year %> A SHA in the Dark, LLC</span>
      <div id="links">
        <%= link_to 'About', about_path %>
        <span id="separator">|</span>
        <%= link_to 'Terms', terms_path %>
      </div>
    </footer>
  </body>
</html>